version: '3.7'
services:

  osticket-app:
    image: tiredofit/osticket
    container_name: osticket-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.evt_osticket.rule=Host(`support.evotel.co.za`)
      - traefik.http.routers.evt_osticket.tls=true
      - traefik.http.routers.evt_osticket.tls.certresolver=lets-encrypt
      - traefik.http.services.evt_osticket.loadbalancer.server.port=80
    volumes:
      - ./data/:/www/osticket
      - ./logs/:/www/logs
    environment:
      - CONTAINER_NAME=osticket-app
      
      - CRON_PERIOD=10

      - DB_HOST=osticket-db
      - DB_NAME=osticket
      - DB_USER=osticket
      - DB_PASS=password

      - SMTP_HOST=localhost
      - SMTP_PORT=25
      - SMTP_FROM=osticket@example.com
      - SMTP_TLS=0
      - SMTP_USER=osticket@example.com
      - SMTP_PASS=password

      - INSTALL_SECRET=somerandomlargecharacterstring
      - INSTALL_EMAIL=osticket@example.com
      - INSTALL_NAME=OSTicket Helpdesk

      - ADMIN_FIRSTNAME=Admin
      - ADMIN_LASTNAME=User
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USER=ostadmin
      - ADMIN_PASS=Password123
    networks:
      - proxy
      - services
    restart: unless-stopped

networks:
  proxy:
    external: true
  services:
    external: true
